CRITICAL - 2021-12-09 20:49:43 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(15): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(29): App\Models\M_login->__construct()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 20:52:25 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(15): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): App\Models\M_login->__construct()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 20:54:15 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(15): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): App\Models\M_login->__construct()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 20:57:08 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(15): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): App\Models\M_login->__construct()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 20:59:09 --> syntax error, unexpected '$this' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:10:01 --> syntax error, unexpected '$this' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:11:56 --> Call to a member function where() on null
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:12:39 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(41): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:15:14 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:16:10 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:19:48 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::where()
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:20:44 --> Object of class CodeIgniter\Database\MySQLi\Connection could not be converted to string
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:20:58 --> Call to a member function where() on null
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:22:40 --> Call to a member function where() on null
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:22:58 --> Call to a member function getWhere() on null
#0 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-09 21:26:47 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1700): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(46): CodeIgniter\Model->__call('getWhere', Array)
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:27:59 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\app\Models\M_login.php(43): CodeIgniter\Database\Config::connect('db3')
#2 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-09 21:28:38 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1700): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(46): CodeIgniter\Model->__call('getWhere', Array)
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:33:12 --> Table 'db_cro.erpuser' doesn't exist
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1978): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(46): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-09 21:37:41 --> Table 'db_cro.erpuser' doesn't exist
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1978): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\cro4\app\Models\M_login.php(47): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#7 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#8 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-09 21:39:48 --> syntax error, unexpected '$db3' (T_VARIABLE)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:40:19 --> syntax error, unexpected '$db3' (T_VARIABLE)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:40:30 --> syntax error, unexpected '$builder' (T_VARIABLE)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:41:44 --> syntax error, unexpected '$grup' (T_VARIABLE)
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\M_lo...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\M_lo...')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(23): spl_autoload_call('App\\Models\\M_lo...')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:42:10 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:42:45 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:45:52 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:47:39 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:50:17 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:51:01 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1190): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Model.php(1648): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(44): CodeIgniter\Model->__get('load')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:53:28 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 21:58:47 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 22:02:44 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 22:03:20 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 22:05:08 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-09 22:17:43 --> Class '\CodeIgniter\Database\PDO\Connection' not found
#0 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Database\Config.php(115): CodeIgniter\Database\Database->load(Array, 'db3')
#1 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\Common.php(234): CodeIgniter\Database\Config::connect('db3', true)
#2 C:\xampp\htdocs\cro4\app\Models\M_login.php(45): db_connect('db3')
#3 C:\xampp\htdocs\cro4\app\Controllers\C_login.php(39): App\Models\M_login->cek_login_v2('aji', 'SSM1234')
#4 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\C_login->aksilogin()
#5 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\C_login))
#6 C:\xampp\htdocs\cro4\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cro4\index.php(46): CodeIgniter\CodeIgniter->run()
#8 {main}
